import { Finding, PageData, Severity } from '../types';
import { CHECK_MAP } from './catalog';

let n=0; const fid=()=>`finding_${Date.now()}_${n++}`;
function add(out:Finding[], page:PageData, checkId:string, message:string, why:string, fix:string, evidence:Record<string,unknown>={}, severity?:Severity){ const c=CHECK_MAP.get(checkId)!; out.push({id:fid(),checkId,category:c.category,severity:severity||c.severity,confidence:'confirmed',title:c.name,pageUrl:page.url,message,why,fix,evidence}); }
function group(values:string[]){ return values.reduce<Record<string,number>>((a,v)=>(a[v]=(a[v]||0)+1,a),{}); }
function isNormalPage(p:PageData){ return !p.resourceKind || p.resourceKind==='page'; }
function analyticsIdentifiers(html:string){
  const ids = [
    ...[...html.matchAll(/\bG-[A-Z0-9]{8,}\b/gi)].map(m=>m[0].toUpperCase()),
    ...[...html.matchAll(/\bGTM-[A-Z0-9]{5,}\b/gi)].map(m=>m[0].toUpperCase()),
    ...[...html.matchAll(/\bUA-\d{4,10}-\d+\b/gi)].map(m=>m[0].toUpperCase()),
  ];
  return [...new Set(ids)];
}

export function runDeterministicRules(pages:PageData[],robots:string):Finding[]{
  const out:Finding[]=[]; if(!pages.length) return out;
  const statusByUrl=new Map(pages.map(p=>[p.url,p.status]));
  for(const p of pages){
    if(p.status>=400&&p.status<500) add(out,p,'CRAWL-006',`This URL returned HTTP ${p.status}.`,'Visitors and search crawlers can hit a dead URL.','Restore the route, redirect it to the closest valid replacement, or remove links that point here.',{status:p.status});
    if(p.status>=500) add(out,p,'CRAWL-007',`This URL returned HTTP ${p.status}.`,'Server errors prevent reliable access and indexing.','Fix the server/application error and retest the URL.',{status:p.status});
    if(!isNormalPage(p)) continue;
    if(!p.url.startsWith('https://')) add(out,p,'CRAWL-002','The audited URL is not HTTPS.','Modern browser features and trust signals depend on secure transport.','Serve the site over HTTPS and redirect HTTP to HTTPS.',{});
    if(p.title.length===0) add(out,p,'META-001','The page has no title element.','Search engines and browser tabs lack a clear page identity.','Add a unique, descriptive title aligned to the page purpose.');
    if(p.title.length>60) add(out,p,'META-003',`Title is ${p.title.length} characters.`,'Long titles can be truncated and become less scannable.','Rewrite the title around the main topic and important qualifier.',{length:p.title.length,title:p.title});
    if(p.title.length>0&&p.title.length<20) add(out,p,'META-004',`Title is only ${p.title.length} characters.`,'Very short titles may waste useful search context.','Make the title specific enough to communicate topic and differentiator.',{length:p.title.length,title:p.title});
    if(!p.description) add(out,p,'META-007','Meta description is missing.','The search snippet may lack intentional messaging.','Add a useful summary with topic, benefit and relevant qualifier.');
    if(!p.lang) add(out,p,'META-013','The HTML lang attribute is missing.','Assistive technology and language processing lose a useful document-level signal.','Set a valid language such as en-GB or en-US.');
    if(!/<meta[^>]+name=["']viewport["']/i.test(p.html)) add(out,p,'META-015','Viewport meta tag is missing.','Mobile browsers may not render the layout as intended.','Add a responsive viewport declaration.');
    if(p.h1.length===0) add(out,p,'META-018','No H1 heading was found.','The page lacks a clear primary heading in the HTML structure.','Add one concise H1 reflecting the page purpose.');
    if(p.h1.length>1) add(out,p,'META-017',`Found ${p.h1.length} H1 elements.`,'Multiple primary headings can weaken document hierarchy and content clarity.','Use one primary H1 and demote other headings to H2 where appropriate.',{count:p.h1.length});
    const emptyHead=p.headings.filter(h=>!h.text); if(emptyHead.length) add(out,p,'META-019',`${emptyHead.length} empty heading element(s) found.`,'Empty headings create noise for users and assistive technology.','Remove empty headings or put meaningful text inside them.');
    let prev=1; for(const h of p.headings){ if(h.level>prev+1){ add(out,p,'META-020',`Heading level jumps from H${prev} to H${h.level}.`,'Unexpected hierarchy makes content structure harder to parse.','Keep headings nested in logical order.',{from:prev,to:h.level}); break;} prev=h.level; }
    if(!p.canonical) add(out,p,'TECH-001','No canonical URL is declared.','Duplicate URL variants can split indexing signals.','Add a self-referencing canonical on indexable pages.',{},'medium');
    else if(new URL(p.canonical,p.url).origin!==new URL(p.url).origin) add(out,p,'TECH-005','Canonical points to another origin.','Cross-domain canonicals can transfer indexing signals away from this page.','Verify the cross-domain relationship is intentional.',{canonical:p.canonical});
    const broken=p.links.filter(l=>!l.external&&statusByUrl.has(l.href)&&((statusByUrl.get(l.href)||200)>=400)); if(broken.length) add(out,p,'LINK-001',`${broken.length} internal link(s) point to discovered error pages.`,'Internal dead links waste crawl paths and create failed user journeys.','Replace or remove the broken destinations.',{links:broken.slice(0,20)});
    const redirects=p.links.filter(l=>!l.external&&statusByUrl.has(l.href)&&[301,302,307,308].includes(statusByUrl.get(l.href)||0)); if(redirects.length) add(out,p,'LINK-003',`${redirects.length} internal link(s) point to redirecting URLs.`,'Unnecessary redirects add latency and dilute clean internal linking.','Link directly to the final destination.',{links:redirects.slice(0,20)});
    const httpLinks=p.links.filter(l=>!l.external&&l.href.startsWith('http://')); if(httpLinks.length) add(out,p,'LINK-005',`${httpLinks.length} internal HTTP link(s) found.`,'Users can be sent from HTTPS pages to insecure variants.','Convert internal links to HTTPS.',{links:httpLinks.slice(0,20)});
    const nameless=p.links.filter(l=>!l.text); if(nameless.length) add(out,p,'LINK-006',`${nameless.length} link(s) have no visible text.`,'Nameless links can be difficult to understand or operate, especially with assistive technology.','Give links an accessible, meaningful name or make decorative elements non-links.');
    const generic=p.links.filter(l=>/^(click here|learn more|read more|here)$/i.test(l.text)); if(generic.length) add(out,p,'LINK-008',`${generic.length} link(s) use generic anchor text.`,'Context-poor anchors provide weak information scent.','Use destination-specific link text where practical.');
    const imgMissing=p.images.filter(i=>i.alt===null); if(imgMissing.length) add(out,p,'MEDIA-001',`${imgMissing.length} image(s) have no alt attribute.`,'Meaningful images need text alternatives; decorative images should be explicitly marked decorative.','Add concise alt text to informative images and alt="" to decorative ones.',{count:imgMissing.length});
    const imgDims=p.images.filter(i=>!i.width||!i.height); if(imgDims.length) add(out,p,'MEDIA-007',`${imgDims.length} image(s) have no explicit dimensions.`,'Missing dimensions can contribute to layout movement during loading.','Provide width and height attributes or reserve stable aspect-ratio space.');
    const brokenImg=p.images.filter(i=>!i.src); if(brokenImg.length) add(out,p,'MEDIA-010',`${brokenImg.length} image reference(s) could not be resolved from HTML.`,'Broken media harms presentation and credibility.','Check media source URLs and asset deployment.',{samples:brokenImg.slice(0,10)});
    const placeholder=/lorem ipsum|your (logo|text) here|placeholder text|example\.com|john doe|testimonials? goes here/i.exec(p.html); if(placeholder) add(out,p,'CONTENT-005','Placeholder/template text was detected.','Unfinished copy makes a production website look incomplete and can leak into search snippets.','Replace or remove all placeholder content.',{match:placeholder[0]});
    const coming=/coming soon|under construction|launching soon/i.exec(p.html); if(coming) add(out,p,'CONTENT-006','Coming-soon language appears on the page.','Users may interpret the page as unavailable.','Remove it after launch or clearly explain availability and timing.',{match:coming[0]});
    if(p.wordCount<180) add(out,p,'CONTENT-008',`Only about ${p.wordCount} words of visible body text were detected.`,'Some page types need more explanation to satisfy user intent and answer objections.','Review the page purpose and add only the information needed to fulfil it.',{wordCount:p.wordCount});
    if((p.html.match(/\b(and\s+){2,}/gi)||[]).length) add(out,p,'CONTENT-004','Repeated-word patterns were detected.','Repeated words can indicate proofreading or generation issues.','Proofread the visible copy and remove accidental repetition.');
    const ids=[...p.html.matchAll(/\bid=["']([^"']+)["']/gi)].map(m=>m[1]); const dup=Object.entries(group(ids)).filter(([,c])=>c>1); if(dup.length) add(out,p,'META-024',`${dup.length} duplicate HTML id value(s) found.`,'Duplicate IDs can break labels, anchors and JavaScript selectors.','Make each id unique or remove IDs that are not needed.',{duplicates:dup});
    if(!p.html.match(/<(header|main|nav|footer)\b/i)) add(out,p,'META-023','No common semantic landmark elements were detected.','Semantic landmarks improve structure for accessibility and maintainability.','Use header, nav, main and footer where they reflect the page structure.');
    const viewportCount=(p.html.match(/<meta[^>]+name=["']viewport["']/gi)||[]).length; if(viewportCount>1) add(out,p,'META-016',`Found ${viewportCount} viewport meta tags.`,'Multiple viewport declarations can produce unpredictable behavior.','Keep one authoritative viewport declaration.');
    if(p.html.length>500000) add(out,p,'PERF-008',`Initial HTML is ${Math.round(p.sourceSize/1024)} KB.`,'Very large HTML increases transfer and parsing work.','Reduce server-rendered markup, duplicated content and embedded data.',{bytes:p.sourceSize});
    const thirdParty=p.scripts.filter(s=>{try{return new URL(s).origin!==new URL(p.url).origin}catch{return false}}); if(thirdParty.length>8) add(out,p,'PERF-015',`${thirdParty.length} third-party scripts are referenced.`,'Third-party JavaScript can add CPU, network and privacy cost.','Audit each script, remove unnecessary vendors and delay non-critical code.',{scripts:thirdParty});
    const dupScripts=Object.entries(group(p.scripts)).filter(([,c])=>c>1); if(dupScripts.length) add(out,p,'PERF-016','Duplicate script references were detected.','Loading the same library more than once wastes bandwidth and can cause conflicts.','Deduplicate script imports.',{duplicates:dupScripts});
    const renderBlockScripts=(p.html.match(/<script\b(?![^>]*\b(?:defer|async)\b)[^>]*>/gi)||[]).length; if(renderBlockScripts>1) add(out,p,'PERF-011',`${renderBlockScripts} script tag(s) lack defer/async.`,'Parser-blocking scripts can delay rendering.','Defer non-critical scripts or load them asynchronously where safe.');
    const styles=p.stylesheets.length; if(styles>4) add(out,p,'PERF-012',`${styles} external stylesheet(s) are referenced.`,'Many render-blocking stylesheets can delay first render.','Bundle critical CSS and reduce blocking stylesheet requests.');
    if((p.html.match(/https?:\/\/(?:localhost|127\.0\.0\.1|staging\.|dev\.)/gi)||[]).length) add(out,p,'SEC-016','Development/internal URL references are present in page source.','Internal endpoints can leak implementation details and break in production.','Remove non-public endpoint references from shipped client code.');
    const sensitive=/api[_-]?key\s*[:=]|secret\s*[:=]|authorization\s*[:=]\s*["']bearer|BEGIN (RSA|OPENSSH|EC) PRIVATE KEY/i.exec(p.html); if(sensitive) add(out,p,'SEC-012','A credential-like pattern was found in page source.','Client-visible credentials can be abused by anyone who can view the page.','Rotate the exposed secret immediately and move sensitive credentials server-side.',{match:sensitive[0]},'critical');
    for(const [hdr,id,fix] of [['strict-transport-security','SEC-003','Send a suitable Strict-Transport-Security header after validating HTTPS behavior.'],['x-content-type-options','SEC-004','Send X-Content-Type-Options: nosniff.'],['content-security-policy','SEC-005','Define a restrictive Content-Security-Policy appropriate for the application.'],['referrer-policy','SEC-007','Set an explicit Referrer-Policy.'],['permissions-policy','SEC-008','Set an explicit Permissions-Policy for browser features.']] as const){ if(!p.headers[hdr]) add(out,p,id,`${hdr} response header is missing.`,'Security headers reduce common browser-side attack and data-leakage risks.',fix); }
    if(/<script[^>]+src=["']http:\/\//i.test(p.html)||/<link[^>]+href=["']http:\/\//i.test(p.html)) add(out,p,'SEC-002','An insecure HTTP asset reference exists on the page.','Mixed content can be blocked by browsers and creates a downgrade surface.','Load all assets over HTTPS.');
    const social=p.links.filter(l=>/linkedin\.com|facebook\.com|instagram\.com|x\.com|twitter\.com/i.test(l.href)); if(social.length===0 && /business|company|agency|consulting|studio|shop|store|clinic|hospital|restaurant|service/i.test((p.title+' '+p.h1.join(' ')))) add(out,p,'TRUST-004','No obvious social profile links were detected on this page.','For some businesses, linked profiles are useful secondary identity signals, but they are not required for every website.','Add relevant official profiles only where they materially support trust.');
    if(/linkedin\.com\/showcase\//i.test(p.html)) add(out,p,'TRUST-015','A LinkedIn Showcase Page URL appears in the site source.','A showcase page may not be the intended company identity destination.','Verify the link points to the correct organization profile.');
    const legal=/privacy|cookie|terms|legal|refund/i.test(p.html); if(!legal && /\b(privacy|terms|legal)\b/i.test(p.html)===false && /contact|about|home/i.test(p.url)) add(out,p,'SEC-024','No obvious privacy/terms/legal link was detected on this page.','Visitors may have difficulty finding required trust and legal information.','Add clearly labelled legal links where applicable.');
    const schemaBlocks=[...p.html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
    if(schemaBlocks.length) { /* positive observation; do not emit a problem finding */ }
    for(const block of schemaBlocks){ try{ JSON.parse(block.trim()); }catch { add(out,p,'SCHEMA-003','A JSON-LD block could not be parsed as valid JSON.','Invalid structured data cannot be reliably consumed.','Validate and fix the JSON-LD syntax.'); } }
    const analyticsIds=analyticsIdentifiers(p.html);
    if(analyticsIds.length===0 && !/privacy|terms|legal|docs|documentation/i.test(p.url)) add(out,p,'ANALYTICS-002','No common analytics/tag identifiers were detected.','Without analytics, it is harder to measure acquisition and conversion behavior, although some sites intentionally avoid third-party analytics.','Confirm whether analytics exists and is intentionally omitted or uses a different implementation.');
    if(analyticsIds.length) add(out,p,'ANALYTICS-001',`Analytics/tag identifiers detected: ${[...new Set(analyticsIds)].join(', ')}.`,'Measurement appears to be installed on this page.','Verify events, consent and conversion goals in the analytics platform.',{ids:[...new Set(analyticsIds)]});
    if(p.url.includes('?')||p.url.match(/%[0-9A-F]{2}/i)) add(out,p,'LINK-024','This URL contains query parameters or encoded characters.','Multiple URL representations can create duplicate crawlable addresses.','Canonicalize or redirect unnecessary parameter variants and ensure navigation uses preferred URLs.');
  }
  // Site-wide duplicate metadata/content signals
  const documentPages=pages.filter(isNormalPage);
  for(const [value,count] of Object.entries(group(documentPages.map(p=>p.title).filter(Boolean)))) if(count>1) add(out,documentPages.find(p=>p.title===value)!, 'META-005', `The title “${value}” appears on ${count} pages.`, 'Repeated titles make pages harder to distinguish in search and browser tabs.', 'Give each indexable page a unique title.', {count,value});
  for(const [value,count] of Object.entries(group(documentPages.map(p=>p.description).filter(Boolean)))) if(count>1) add(out,documentPages.find(p=>p.description===value)!, 'META-009', `The same meta description appears on ${count} pages.`, 'Repeated descriptions provide little page-specific context.', 'Write unique descriptions for pages where a search snippet matters.', {count});
  const h1Groups=group(documentPages.map(p=>p.h1[0]).filter(Boolean)); for(const [value,count] of Object.entries(h1Groups)) if(count>1) add(out,documentPages.find(p=>p.h1.includes(value))!,'TECH-009',`The H1 “${value}” appears on ${count} pages.`,'Repeated primary headings can indicate duplicate or weakly differentiated templates.','Differentiate page headings around the actual page purpose.',{count,value});
  return out;
}

export function summarizeFindings(findings:Finding[]){ const bySeverity=findings.reduce<Record<string,number>>((a,f)=>(a[f.severity]=(a[f.severity]||0)+1,a),{}); const byCategory=findings.reduce<Record<string,number>>((a,f)=>(a[f.category]=(a[f.category]||0)+1,a),{}); return {bySeverity,byCategory,total:findings.length}; }
